Update patch set 1
Patch Set 1:

Submitted too soon, now the x64 build fails with:
ninja -t msvc -e environment.amd64 -- cl.exe /nologo /showIncludes -DNDEBUG -I../.. -I../../third_party/mini_chromium/mini_chromium -I../../compat/win -I../../third_party/gtest/gtest/googletest/include /wd4201 /DNOMINMAX /DUNICODE /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_HAS_EXCEPTIONS=0 /D_UNICODE /FS /W4 /WX /Zi /bigobj /wd4100 /wd4127 /wd4324 /wd4351 /wd4577 /wd4996 /GL /O2 /Ob2 /Oy- /Zc:inline /d2Zi+  /c ../../snapshot/minidump/process_snapshot_minidump_test.cc /Foobj/snapshot/minidump/snapshot_test.process_snapshot_minidump_test.obj /Fd"obj/snapshot/snapshot_test_cc.pdb"
../../snapshot/minidump/process_snapshot_minidump_test.cc(326): error C2220: warning treated as error - no 'object' file generated
../../snapshot/minidump/process_snapshot_minidump_test.cc(326): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
../../snapshot/minidump/process_snapshot_minidump_test.cc(1069): warning C4267: '=': conversion from 'size_t' to 'ULONG32', possible loss of data

This is probably going to require a couple more updates. You can hold off on the review.

Patch-set: 1
Reviewer: Gerrit User 1238767 <1238767@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>