Roll crashpad/third_party/gtest/gtest/ eb78ee170..e3f0319d8 (232 commits)
https://chromium.googlesource.com/external/github.com/google/googletest/+log/eb78ee170ac9..e3f0319d89f4

This CL also removes references to gmock-generated-matchers.h, which was
removed from googletest in commit
41b5f149ab306e96b5b2faf523505d75acffd98a, and to
gmock-generated-function-mockers.h, which was removed from googletest in
commit fbf67a70d07543f40832d0cd7a58f304bc6ab1d1.

$ git log eb78ee170..e3f0319d8 --date=short --no-merges --format='%ad %ae %s'
130e5aa86a7a Merge pull request #2 from google/master
6fd262ecf787 Prepare for Bazel incompatible changes
800c9b30168f Update Bazel on Windows
2c2c9e33573d remove a custom implementation of std::add_lvalue_reference
11471da7938b remove a custom implementation of std::enable_if
e2c06aa2497e remove a custom implementation of std::iterator_traits
364839ab142e remove a custom implementation of std::remove_const
da76d01b984f remove a custom implementation of std::is_reference
6a015ca1cb4e reuse IndexSequence from googletest
44de8697835d remove a dead metafunction
27e17f7851e2 Googletest export
410b52985e3d Googletest export
fcffabb5beb8 Googletest export
30e58a89a42b Merge pull request #2381 from Yannic:fix_bazel
d5e9e0c38f85 Merge pull request #2397 from kuzkry:custom-type-traits-is_reference
c9ccac7cb734 Googletest export
7bd4a7f3e9ae restore mistakenly removed iffs in their explicit form
d1ad644db4b9 Googletest export
fb49e6c16449 Merge pull request #2393 from kuzkry:custom-type-traits-remove_const
f8e9b3767ff8 remove references to autotools and combine gTest&gMock sections
9bf34ace7194 Merge pull request #2400 from kuzkry:custom-type-traits-enable_if
c6d884096ae5 Merge pull request #2401 from kuzkry:custom-type-traits-add_lvalue_reference
46525e1e5dfc Merge pull request #2394 from kuzkry:custom-type-traits-duplication-of-custom-index_sequence
db1b739943e9 Googletest export
ed2eef654373 Googletest export
38ce18e8e662 post-review to db1b7399 (#2396)
6a3d632f40a1 Googletest export
fdd6a1dc8c74 Merge pull request #2382 from kuzkry:dead-metafunction
85f059f03d56 Merge pull request #3 from google/master
d9c55a48eddb Merge pull request #2426 from kuzkry:#2396-postreview
eb56ee5a28b4 Googletest export
a648da952b79 Merge pull request #2420 from kuzkry:remove-autotools-section
565f1b848215 Merge pull request #2398 from kuzkry:custom-type-traits-iterator_traits
ab8f346b076f Googletest export
6123df929dba Googletest export
3f05f651ae36 Googletest export
c2b2cd8883f5 Googletest export
62a109a2ffe6 Googletest export
3a4503986247 Googletest export
bafa644c182e remove a dead function
838ea5cea301 remove GTEST_HAS_STD_STRING
33a0d4f6d76a Googletest export
0cd3fbc8abe6 change includes in gtest-port.h
274afe50cf57 Googletest export
ac24edd6e061 Googletest export
c7a03daa99e7 Merge pull request #2387 from kuzkry:iff
c96da8fea82e change usings
cad3bc46c2ba Googletest export
f2fb48c3b3d7 Googletest export
7c2bd3af981e square away the stuff that hasn't been merged in a manual review
3339b97c6a7f square away the stuff that hasn't been merged in a manual review
90a8ab70a1f6 mention the existing support for wide strings in string matchers
e0d16aa33662 remove GTEST_ARRAY_SIZE_
2460f97152c9 Add many missing override keywords
c78ea26f2008 Bump llvm version to 4 so brew can work again
076c46198fe1 Googletest export
bf0fe874a27b Googletest export
a783ade7c244 Googletest export
cb3f7ce1deef Googletest export
72adf7a4155b Googletest export
dc1ca9ae4c20 Googletest export
51f7396d4058 Fix typo in documents
68319c19eb01 Googletest export
4105eb726341 Googletest export
703bd9caab50 (tag: v1.10.x, tag: release-1.10.0) Googletest export
76a560c81cfe Googletest export
5126ff48d9ac Revert "Use pcfiledir for prefix in pkgconfig file"
b96832a44b49 Add documentation for pkg-config in cross-compilation settings
4360e4267c1e Merge pull request #2491 from SoapGentoo:fix-GNUInstallDirs-pkg-config
2ed2211db99a Use FormatFileLocation for streaming file and line
3f5a8c6ee6ce Merge pull request #2495 from hyukmyeong:typo
10c1d8c4faed Use the verbatim noexcept spec in MOCKED_METHOD
0eadff8a932d Fix spacing
872b9ceb6045 Avoid comma operator
7f8617a7c532 Switch to free function to avoid GCC bug
20255e6f4099 Use declval in noexcept expression
cd17fa2abda2 Merge pull request #2475 from peterbarker:pr/google-add-override
de69803b1e38 Mention Cornichon as a related open source project
cb1d5db1a104 Merge pull request #2448 from kuzkry:bad-googletest-export
5395345ca4f0 Merge pull request #2497 from thejcannon:handle_null_filename
20b5b8ecc7a8 Googletest export
58c71977611c Merge pull request #2505 from zebmason:cornichon
bc996e0817d8 Made noexcept condition more exciting
31406d79090e chore:  update version
9b9700247d46 clean-up broken paths for PlatformIO
ed78e54f38ab Googletest export
a4a5a7c768ce Googletest export
37905b9d8c8f Merge pull request #2498 from thejcannon:noexcept_spec
eafd2a91bb0c Merge pull request #2456 from kuzkry:gtest-port-clean-up_breaking-changes
a3ca5b9e0bf9 Googletest export
ba513d2c9525 Merge pull request #2498 from thejcannon:noexcept_spec
c081ceebfb6f Workaround MSVC VA_ARGS weirdness
c1e8e71aab60 Add a compile test
d935e8e3edaf Fix preprocessor tests
fe112cfee7e7 Replace compile-test with preprocessor test
5fe523361243 Removing extraneous test
40a6b9662199 feat: Add support for ESP8266 platform
c2206b05aa0f Add ESP8266 configs to PlatformIO build
f8961b99f4c3 Evaluate and cat NARG in different macros
3e813465a46b Removing extraneous parenthesis
84a5ae8b8560 Update to distinguish prelease purpose of this fork.
3cddd56e195b Add more override keywords
e1b67b07f7bd Avoid recursive macros
778733f9ecdd feat: Add ESP8266 support
9e466f1eb0fa Merge pull request #2510 from ciband:chore/update_pio_version
4c25e2b87fcb Googletest export
bdc29d5dc19d Merge pull request #2421 from kuzkry:cleanup-for-regex
cbf019de22c8 [googletest] Output skip message
2995ca563d76 Merge pull request #2507 from roblub:master
bbe4b7363bba Googletest export
1f9edcd96981 Googletest export
f966ed158177 Googletest export
5f92697d46ae Fix Issue 2418
f164a9e23c0f Remove extra space
011c4e23d525 Googletest export
8ce64c084d83 Merge pull request #2454 from kuzkry:gtest-port-clean-up_dead-function
a5216dd1a9f3 Merge pull request #2511 from kuzkry:PlatformIO-clean-up
611a321a6e64 Googletest export
de1128355464 Merge pull request #2444 from kuzkry:remove-GTEST_ARRAY_SIZE_
8c91ecef292e Merge pull request #2517 from snarkmaster:master
b11fb80e9e94 Prevent using ReturnRef on reference to temporary
f1afeaa64348 Googletest export
19a3bbce512d Added tests verifying that temporaries are accepted by ReturnRef
37590da6c08f Added more tests to verify: ReturnRef not accept temporary
aa1146da8169 Googletest export
8bab7883a676 Merge pull request #2514 from thejcannon:msvc_macro_issue
1110c471cadf Merge pull request #2522 from cloudrex:patch-1
676d0444bf95 Revert "Merge pull request #2498 from thejcannon:noexcept_spec"
37f322783175 Googletest export
6e87238c9b14 remove BiggestInt
d072682119f8 Tests simplified and names corrected (POD->scalar)
5ff72f5295f3 Apply 80chars limit
208c2f6b6076 variable names corrected (followed google coding style)
540835fa687e Merge pull request #2515 from ciband:feat/support_esp8266
eed64b5fc6c0 replace autogenerated TypesX classes by variadic ones
e3a9a567d826 replace autogenerated TemplatesX classes by variadic ones
a7083564d550 remove gtest-type-util.h.pump
002905f29fc9 move the pumping script to googlemock
1a49b67aebe9 update CONTRIBUTORS
a8b1a66cfda3 Merge pull request #2388 from kuzkry:remove-gtest-type-util.pump
a1f71dd56df4 Googletest export
b5fb5ba05cb6 Merge pull request #2527 from PiotrNycz:gmock_prevent_return_ref_to_store_temporaries_2
757d39a79bcb Googletest export
755f853c6be9 Googletest export
2bee6da24e9f Googletest export
fff8dabbf6c5 Googletest export
ba33a8876c3e Googletest export
f626deda19e5 Added special catch for std::exception in GTEST_TEST_NO_THROW_
0a03480824b4 Googletest export
e2fc3a9c9cb8 Googletest export
2db3df9c4f82 Googletest export
057ee5063d00 Merge pull request #2533 from thejcannon:noexcept_spec
e8a82dc7ede6 Merge pull request #2453 from kuzkry:gtest-port-clean-up_kMaxBiggestInt
523ad489efc3 update pump_manual.md
442f45b376f5 pump.py: add support for Python 3
f658561ef253 fix a typo
8697709e0308 Merge pull request #2453 from kuzkry:gtest-port-clean-up_kMaxBiggestInt
f9665846e405 update gen_gtest_pred_impl.py
f79ac2ce0e78 change incorrect comments
6caa879a42d9 pkg-config: Remove pthread link flag from Cflags
3e062a6efe7a Merge pull request #2373 from Youw:master
54978626b40f Merge pull request #2547 from kuzkry:typo
8aedd597af6b Merge pull request #2548 from kuzkry:update-pump-manual
e08a4602778b Merge pull request #2549 from kuzkry:pump-support-for-python-3
681454dae48f Googletest export
d5707695cb02 Googletest export
dee725b05332 add documentation for the premature-exit-file protocol
11440f27c66d Merge pull request #2556 from ienorand:avoid-pkg-config-lpthread-cflag
f73898f3ffd4 Merge pull request #2554 from kuzkry:update-gen_gtest_pred_impl
c27acebba3b3 Merge pull request #2521 from Sinclair-John:master
0c469a5a065e Fix FlatTuple compilation on older msvc.
dcdb65065f41 Fix internal memory leak in Windows _Crt report.
50cfbb726b26 Googletest export
4bf466236dbe Googletest export
200ff599496e Merge pull request #2569 from bgianfo:master
6a9d6d5c28a7 Fix compile break for Microsoft Visual Studio 2017 v141
2241be0c3f24 remove g++ 3.3 workaround: using on operator<<
e1dd49835ef2 remove g++ 2.95.0 workaround: no space after first comma in macros
a91e4e73b702 remove stale comments about older GCC versions
21d276b5c42d remove MSVC workaround: accessing namespace scope from within nested classes
a5136dbdd21e remove MSVC workaround: error C2665
ecefcbd4aa71 remove MSVC workaround: warning 4355
6748df1eab1d remove MSVC workaround: cease const dropping
e0c80b0a6e51 consistency fix for SafeMatcherCastImpl member functions
bbbc5d8a4b90 remove Nokia's Symbian compiler workaround: SafeMatcherCastImpl
298a40f023e6 remove MSVC workaround: wmain link error in the static library
a909becdc599 unify googletest and googlemock main functions
717ce7feb872 Googletest export
af71b6607f9e Merge pull request #2570 from xieyubo:1.10
679bfec6db73 Googletest export
838a32845c64 Fixed typo
5a62d400e057 README.md: added Catch2 and Google Test Explorer
51545ee515fc Googletest export
a32a20009473 Merge pull request #2588 from kuzkry:remove-workaround_g++-incorrect-comments
7a8a5bcec005 Merge pull request #2591 from kuzkry:remove-workaround_g++-using-on-operator<<
be74b4b2e0d1 Googletest export
db13ff1f0bd5 Merge pull request #2597 from kuzkry:remove-workaround_Nokia-Sybian-SafeMatcherCastImpl
0361bdf591dd Merge pull request #2596 from kuzkry:remove-workaround_msvc-wmain-link-error
39803f3c51d2 Merge pull request #2593 from kuzkry:remove-workaround_msvc-namespace-scope-from-nested-class
34e92be31cf4 Merge pull request #2604 from matepek:readme-update-with-opensource-proj
b8a92f7c86e4 Rename test case to test suite
967d8e05c2f0 Revert "unify googletest and googlemock main functions"
3957b8898b58 Revert "remove MSVC workaround: wmain link error in the static library"
b155875f32dc Merge pull request #2583 from ChristophStrehle:master
11a9482f84ac Merge pull request #2607 from oyefremov:patch-1
52825d78aac6 Merge pull request #2603 from maximilianschwab:patch-1
ae8d1fc81b14 Googletest export
cf75d4b92ecc Googletest export
1d563578c86f Merge pull request #2594 from kuzkry:remove-workaround_msvc-unneeded-const-dropping
2002f267f05b Googletest export
9ed99c6c837a Googletest export
78fdd6c00b8f Merge pull request #2609 from kuzkry:revert-2596
20b8e7a1c827 Activate GNU extensions in case of MSYS generator
6251071a20e8 Googletest export
a3097c826e4d Merge pull request #2592 from kuzkry:remove-workaround_msvc-error-C2665
88ba008c234a Merge pull request #2595 from kuzkry:remove-workaround_msvc-warning-4355
d442089d53ce Googletest export
d8eeb9760afc Googletest export
d16f86ff1cac Googletest export
5b162a79d49d Merge pull request #2589 from kuzkry:remove-workaround_g++-no-space-after-first-macro-argument
d2016469064b Workaround VS bug w.r.t empty arguments to macros
4b7809c2f523 Revert "Googletest export": Remove test for empty prefix
1800a38fb7d8 Revert "Googletest export": disallow empty prefix
0a0c82662992 Googletest export
d166e0948384 Merge pull request #2590 from kuzkry:remove-workaround_g++-stale-comments
9d8222ad6672 Disable move constructor and assignment operator for test classes.
77b3a250ea9e Review notes: Return T& from assignment operators
05701fee2896 Deleted functions as part of public interface
cc05a3ca014b Define default destructor for test classes
bf31ed376ab1 Make move operation noexcept.
6f1a8ffde934 Googletest export
d0a521255eb5 Googletest export
008629ae2163 Merge pull request #2624 from ShabbyX:master
a13a0626188b Googletest export
fbe34cecf4ff Merge pull request #2639 from trzecieu:trzeci/move_ctor_assign
153909f09633 Googletest export
0d98d87e1069 Googletest export
07ab939af757 Merge pull request #2632 from Kravlalala:cmake/mingw_msys_build
306f3754a71d Googletest export
4b9c1691c4b7 Googletest export
8417b7332210 Googletest export
c901f67ddf8a Googletest export
d854bd6acc47 Googletest export
3aa538cbfcc6 fix unit test failure on NoShortCircuitOnFailure and DetectsFlakyShortCircuit when GTEST_HAS_RTTI is 1
c7137f0b8422 Use IsReadableTypeName IsReadableTypeName in OfType function in gmock-matchers_test.cc
aa4315646b22 Remove exclusion of *-main and*-all targets
ed16134fb313 Googletest export
0b024bd91a14 Googletest export
7a8591e6e4e2 Googletest export
3e79d366e380 Googletest export
5336106b66db Googletest export
8b4817e3df37 Googletest export
18b67bfc58b1 Googletest export
c59c7bab5056 Merge pull request #2672 from ivan1993br:ivan1993br-platformio_update
9417fb401a57 Merge pull request #2665 from bysreg:fix_noshortcircuitfailure_detectsflakyshortcircuit_test
d01e356e155a Googletest export
10b1902d893e Googletest export
c378d7eb9308 remove a dead reference to the Autotools script
22397f28ef57 Googletest export
f1a6db9d4a8c Googletest export
87061810f4c7 Googletest export
7413280c52c1 Googletest export
d6ce39edf612 Googletest export
38f6608e8790 Googletest export
7bc671b8e0de Googletest export
572e261b6075 Googletest export
74b44b2d0fc2 Googletest export
4f6609129a2f Googletest export
d02e2772750f Googletest export
11d9834e98c1 Googletest export
fbf67a70d075 Googletest export
2d6d7a01c9ce Googletest export
41b5f149ab30 Googletest export
139fa202c938 Googletest export
360f5f70a3ff Googletest export
56de7cc8b554 Googletest export
d0930731d601 Googletest export
6f5fd0d7199b Googletest export
23b2a3b1cf80 Googletest export
04e52ebe7816 Fixed warnings
fd538161f484 Googletest export
909b1ccfcacc Googletest export
e588eb1ff9ff Googletest export
a1b0173df92b Make sure IsATTY does not clobber errno.
cfb5ef4e7dc0 Googletest export
878bd92e0fef Merge pull request #2716 from kuzkry:autotools-leftover
3de76551e0f0 Merge pull request #2722 from JohanMabille:warnings
0bf8ea3065f7 Googletest export
230afdb24e0f Googletest export
227faf41db5e Googletest export
c43f7100f084 Googletest export
482ac6ee6342 Googletest export
e41f31f2af3a Add tests for MockFunction deduction (#2277)
53740ebc21d5 Add support for std::function in MockFunction (#2277)
dbe804f98621 Merge pull request #2746 from Romain-Geissler-1A:master
749148f1accc Googletest export
08347d7a1604 Swap settimer and sigaction calls to avoid SIGPROF
82e5767f7812 remove dead code in googletest-output-test
acabdf65fba1 remove chapters on Autotools, Meson and plain Makefiles
1ced315a483f Googletest export
67cc66080d64 Merge pull request #2350 from adambadura:MockFunctionFromStdFunction
01e4fbf5ca60 Merge pull request #2764 from kuzkry:googletest-output-test-dead-code
dc82a33473dd Merge pull request #2765 from kuzkry:unsupported-build-systems
61f010d703b3 Googletest export
c344cb5a8d2b Googletest export
7084afda5aa3 Merge pull request #2762 from pkryger:avoid_sigprof
e3f0319d89f4 Merge pull request #2715 from kuzkry:document-premature-exit-file-protocol

Created with:
  roll-dep crashpad/third_party/gtest/gtest

Bug: 1070043
Change-Id: I39ab84ab931fa469cf8922a2d33d9b2b4e04cf4e