Update patch set 1
Patch Set 1:

Your comments RE: <winbase.h> are correct on principle. However, Bazel enforces a strict policy of "include-what-you-use", and my tests show that leaving this line out causes the following errors:

crashpad/test/filesystem.cc(66,32):  error: use of undeclared identifier 'SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE'
                               SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE)) {
                               ^
crashpad/test/filesystem.cc(67,16):  error: use of undeclared identifier 'SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE'
        return SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE;

I can work on this from the Bazel end instead if needed, but directly including <winbase.h> in addition to <windows.h> did seem to fix things.

Patch-set: 1
Reviewer: Gerrit User 1317891 <1317891@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>