Update patch set 3
Patch Set 3:

I have compiled crashpad source code in centos7.6 and tried to use them in ubutu 18.04. Then i faced an error
undefined reference to `crashpad::CrashpadClient::SetFirstChanceExceptionHandler(bool (*)(int, siginfo_t*, ucontext_t*))'

I realised there is a difference in ucontext_t structure between both glibc versions. I changed to void* so that the user defining firstchanceExceptionhandler will be free to typecast it if he intends to use ucontext_t

Patch-set: 3
Reviewer: Gerrit User 1174099 <1174099@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1172779 <1172779@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false