Fix for cdb tests
There's a problem running crashpad_handler, but I'm not sure what it is.
I think an exception is getting swallowed because my handling of
`handler` was incorrect, so correctly initialize that to see the
exception.

https://build.chromium.org/p/client.crashpad/builders/crashpad_win_x64_rel/builds/36/steps/run%20tests/logs/stdio
"""
UnboundLocalError: local variable 'handler' referenced before assignment
"""

(I also realized the !locks code hasn't landed yet so disable those tests
for now too.)

R=mark@chromium.org
BUG=crashpad:46

Review URL: https://codereview.chromium.org/1391023006 .