android: Fix gmock-using tests’ use of MOCK_METHODn() with clang
This was already addressed by disabling a warning, but was only
effective for macOS and non-Android Linux. The comment for the existing
fix, which is now being applied to Android:

> The MOCK_METHODn() macros do not specify “override”, which triggers
> this warning in users: “error: 'Method' overrides a member function
> but is not marked 'override'
> [-Werror,-Winconsistent-missing-override]”.  Suppress these warnings,
> and add -Wno-unknown-warning-option because only recent versions of
> clang (trunk r220703 and later, version 3.6 and later) recognize it.

Also see https://crbug.com/428099.

The errors being encountered since 3983b80ca2fc were:

util/file/file_reader_test.cc:48:23: error: 'Read' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  FileOperationResult Read(void* data, size_t size) {
                      ^
util/file/file_reader.h:39:31: note: overridden virtual function is here
  virtual FileOperationResult Read(void* data, size_t size) = 0;
                              ^
util/file/file_reader_test.cc:53:16: error: 'Seek' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  MOCK_METHOD2(Seek, FileOffset(FileOffset, int));
               ^
util/file/file_seeker.h:31:22: note: overridden virtual function is here
  virtual FileOffset Seek(FileOffset offset, int whence) = 0;
                     ^

Bug: crashpad:30
Test: crashpad_util_test FileReader.*
Change-Id: I10894efdafc0da965e3780219f2e4c1f13f9b99e