Update patch set 1
Patch Set 1:

K, an infra bot scolded me with this message:

Some configs in revision ae8fe2d in crashpad/crashpad repo have validation errors. luci-config had to reject all configs in this revision.

ERROR: rietveld or gerrit is required
Please correct these errors. If you have questions, ask CCed people.

If a .proto file was updated recently, the service performing validation of "invalid" file(s) may need to be redeployed.

-Your friendly luci-config service

I see "gerrit {}" specified in other cg.cfg files, notably https://cs.chromium.org/chromium/infra/config/cq.cfg?type=cs&q=gerrit+cq.cfg&l=13.

Patch-set: 1
Reviewer: Mark Mentovai <1174099@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Sigurður Ásgeirsson <1177549@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>