tvOS: Remove LOG() call from CrashHandler::DoInitialize()
This fixes a compilation error when building Crashpad in Chromium:

../../third_party/crashpad/crashpad/client/crash_handler_tvos.cc:60:9: error: use of undeclared identifier 'ERROR'
   60 |     LOG(ERROR) << "Unable to install crash handlers";
      |         ^~~~~

But most importantly, the call itself was not very useful since
InstallCrashHandlers() will already show a more descriptive error
message if sigaction() fails.

Bug: 405140658
Change-Id: If20186017e8202ddd355a416c2cc7ba8b8dd64cc
Reviewed-on: https://chromium-review.googlesource.com/c/crashpad/crashpad/+/6551426
Reviewed-by: Mark Mentovai <mark@chromium.org>
Commit-Queue: Raphael Kubo da Costa <kubo@igalia.com>