Have snapshot_test_lib depend on compat
Needed on Windows for sys/time.h.

d:\src\crashpad\crashpad\snapshot\test\test_process_snapshot.h(19) : fatal error C1083: Cannot open include file:
'sys/time.h': No such file or directory

R=mark@chromium.org
BUG=crashpad:1

Review URL: https://codereview.chromium.org/897973003