Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > The new failures are related to this change:
> > > > 
> > > > FAILED: obj/util/fuchsia/util.koid_utilities.o 
> > > > ../../third_party/fuchsia/clang/linux-amd64/bin/clang++ -MMD -MF obj/util/fuchsia/util.koid_utilities.o.d -DCRASHPAD_ZLIB_SOURCE_EMBEDDED -Igen/third_party/crashpad/crashpad -I../.. -I../../compat/non_mac -I../../compat/non_win -Igen/fidl/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_base/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/async/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp_base/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp_sync/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fit/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/zx/include -I../../third_party/mini_chromium/mini_chromium -I../../third_party/zlib/zlib -Wall -Wendif-labels -Werror -Wextra -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wsign-compare -fno-exceptions -fno-rtti -fno-strict-aliasing -fobjc-call-cxx-cdtors -fstack-protector-all -fvisibility-inlines-hidden -fvisibility=hidden -Wheader-hygiene -Wnewline-eof -Wstring-conversion -fPIC -Wimplicit-fallthrough --sysroot=../../third_party/fuchsia/sdk/linux-amd64/arch/x64/sysroot -isystem ../../third_party/fuchsia/sdk/linux-amd64/pkg/fdio/include --target=x86_64-fuchsia -Wexit-time-destructors -std=c++14 -c ../../util/fuchsia/koid_utilities.cc -o obj/util/fuchsia/util.koid_utilities.o
> > > > ../../util/fuchsia/koid_utilities.cc:21:10: fatal error: 'task-utils/get.h' file not found
> > > > #include <task-utils/get.h>
> > > >          ^~~~~~~~~~~~~~~~~~
> > > 
> > > Yes, why can I build this locally but it fails here? Once adding "//zircon/public/lib/task-utils" to the BUILD.gn file I didn't see this error anymore.
> > 
> > Ah, I guess it's because the build is hitting the "crashpad_is_in_chromium" case. I hope my change addresses this, but not sure how to verify.
> 
> No crashpad_is_in_chromium is a third case that is neither covered by the Crashpad bots nor by `fx build` in a Fuchsia checkout.
> 
> - `fx build` in a Fuchsia checkout will trigger the "crashpad_is_in_fuchsia" path that you have changed: https://chromium.googlesource.com/crashpad/crashpad/+/master/third_party/fuchsia/BUILD.gn#17
> - `ninja` in a Crashpad checkout (either local or on the Crashpad bots) will trigger the "else" path that hasn't changed and therefore fails: 
> https://chromium.googlesource.com/crashpad/crashpad/+/master/third_party/fuchsia/BUILD.gn#35
> - Building Crashpad in Chromium targeting Fuchsia will trigger the "crashpad_is_in_chromium" path, but I don't know how to test that.
> 
> Because you don't seem to have access to Crashpad CQ to kick off a dry run, do you mind checking out Crashpad locally following https://chromium.googlesource.com/crashpad/crashpad/+/master/doc/developing.md#getting-the-source-code and then run:
> ```
> $ gn gen out/fuchsia --args='target_os="fuchsia" target_cpu="x64" is_debug=true'
> $ ninja -C out/fuchsia
> ```
> As long as this fails, the Crashpad bots won't pass.

After following the instructions and performing that last ninja step, I get the following error:
ninja: error: '../../third_party/fuchsia/sdk/linux-amd64/tools/fidlc', needed by 'gen/fidl/include/fuchsia/mem/c/client.cc', missing and no known rule to make it

Any idea what I need to do to fix that?

Patch-set: 3
Reviewer: Gerrit User 1361171 <1361171@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0