Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > The new failures are related to this change:
> > 
> > FAILED: obj/util/fuchsia/util.koid_utilities.o 
> > ../../third_party/fuchsia/clang/linux-amd64/bin/clang++ -MMD -MF obj/util/fuchsia/util.koid_utilities.o.d -DCRASHPAD_ZLIB_SOURCE_EMBEDDED -Igen/third_party/crashpad/crashpad -I../.. -I../../compat/non_mac -I../../compat/non_win -Igen/fidl/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_base/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/async/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp_base/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fidl_cpp_sync/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/fit/include -I../../third_party/fuchsia/sdk/linux-amd64/pkg/zx/include -I../../third_party/mini_chromium/mini_chromium -I../../third_party/zlib/zlib -Wall -Wendif-labels -Werror -Wextra -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wsign-compare -fno-exceptions -fno-rtti -fno-strict-aliasing -fobjc-call-cxx-cdtors -fstack-protector-all -fvisibility-inlines-hidden -fvisibility=hidden -Wheader-hygiene -Wnewline-eof -Wstring-conversion -fPIC -Wimplicit-fallthrough --sysroot=../../third_party/fuchsia/sdk/linux-amd64/arch/x64/sysroot -isystem ../../third_party/fuchsia/sdk/linux-amd64/pkg/fdio/include --target=x86_64-fuchsia -Wexit-time-destructors -std=c++14 -c ../../util/fuchsia/koid_utilities.cc -o obj/util/fuchsia/util.koid_utilities.o
> > ../../util/fuchsia/koid_utilities.cc:21:10: fatal error: 'task-utils/get.h' file not found
> > #include <task-utils/get.h>
> >          ^~~~~~~~~~~~~~~~~~
> 
> Yes, why can I build this locally but it fails here? Once adding "//zircon/public/lib/task-utils" to the BUILD.gn file I didn't see this error anymore.

Ah, I guess it's because the build is hitting the "crashpad_is_in_chromium" case. I hope my change addresses this, but not sure how to verify.

Patch-set: 3
Reviewer: Gerrit User 1361171 <1361171@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0