Add cpp-httplib local modification for BoringSSL compatibility
In some build configurations, sk_X509_OBJECT_num (from BoringSSL)
returns a size_t. Comparing this directly against a signed int loop
counter triggers -Werror,-Wsign-compare.

This patch moves the count into a local int variable so the compiler
uses implicit conversion to ensure type consistency during the loop
comparison.

Upstream pull request created here:
  https://github.com/yhirose/cpp-httplib/pull/2355

Full error: In file included from
../../third_party/crashpad/crashpad/util/net/http_transport_test_server.cc:42:
../../third_party/crashpad/crashpad/third_party/cpp-httplib/cpp-httplib/httplib.h:10923:21:
error: comparison of integers of different signs: 'int' and 'size_t'
(aka 'unsigned long') [-Werror,-Wsign-compare]
 10923 |   for (int i = 0; i < sk_X509_OBJECT_num(objs); i++) {
       |                   ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated from:
https://ci.chromium.org/ui/p/chromium/builders/try/linux-chromeos-compile-dbg/2519055/overview

Change-Id: If24ef33b3838bf90e1f1c79a3869892aa9209c7c
Reviewed-on: https://chromium-review.googlesource.com/c/crashpad/crashpad/+/7563115
Reviewed-by: Mark Mentovai <mark@chromium.org>
Commit-Queue: Justin Cohen <justincohen@google.com>