list headers' includes as public dependencies
* introduced in https://chromium-review.googlesource.com/c/1278829
* this blocks the rollup in Fuchsia:
../../third_party/crashpad/test/scoped_guarded_page_posix.cc:20:10: fatal error: 'base/process/process_metrics.h' file not found
../../third_party/crashpad/util/process/process_memory_test.cc:21:10: fatal error: 'base/process/process_metrics.h' file not found

Change-Id: I7ad5cc96cb7cdaf9100dac5cbe49885b3d561ec5