Use x30 register instead of LR, which GCC doesn't seem to understand
When tested with GCC 6, it couldn't to understand LR register.
Thus, use x30 instead.

The error this patch fixes is the following:

Error: operand 1 must be an integer register -- `str LR,[x0,#0x1b8]'

Test: compile for aarch64
Change-Id: Icf1199254c6a29f72b6d2fa7940e1f33259a728b