Update patch set 3
Patch Set 3:

Heh, there's two different failures, one might look familiar! :(

commit 8b085f0d2168e6e54712d295dcf26feac92bb9fc
Author:    Mark Mentovai <mark@chromium.org>
Committed: Wed Nov 11 12:28:15 2015 -0500

    Fix warnings encountered in MSVC build of gtest/gmock tests
    
    This fixes these warnings:
    
    …\gtest\googletest\test\gtest-port_test.cc(78) : error C2220: warning treated as error - no 'object' file generated
    …\gtest\googletest\test\gtest-port_test.cc(78) : warning C4309: 'static_cast' : truncation of constant value
    …\gtest\googletest\test\gtest-port_test.cc(79) : warning C4309: 'static_cast' : truncation of constant value

Patch-set: 3
Reviewer: Scott Graham <1144260@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0